target 'iosApp' do
  use_frameworks!
  platform :ios, '17.0'
  pod 'presentation', :path => '../presentation'
  pod 'Sentry'

end

target 'KlardropMac' do
  use_frameworks!
  platform :osx, '14.0'
  pod 'presentation', :path => '../presentation'
  pod 'Sentry'
end
