@file:OptIn(kotlinx.cinterop.ExperimentalForeignApi::class)

package com.carlom.klardrop.common.trust.secretstore

import com.carlom.klardrop.common.utils.ensureDirectory0700
import com.carlom.klardrop.common.utils.log
import com.carlom.klardrop.common.utils.readFileBytes
import com.carlom.klardrop.common.utils.writeFile0600
import dev.whyoleg.cryptography.BinarySize.Companion.bytes
import dev.whyoleg.cryptography.CryptographyProvider
import dev.whyoleg.cryptography.algorithms.AES
import dev.whyoleg.cryptography.algorithms.PBKDF2
import dev.whyoleg.cryptography.algorithms.SHA256
import dev.whyoleg.cryptography.random.CryptographyRandom
import kotlinx.cinterop.pointed
import kotlinx.cinterop.toKString
import kotlinx.coroutines.runBlocking
import platform.posix.getenv
import platform.posix.geteuid
import platform.posix.getpwuid
import platform.posix.unlink

/**
 * Last-resort fallback that AES-GCM-encrypts the secret with a key
 * derived from the local machine + user identity, then writes the
 * ciphertext under [appDir].
 *
 * File layout (single file per account, e.g. `device-private-key.aes`):
 *   magic[4] = "KAES"
 *   version[1] = 0x01
 *   salt[16]
 *   iv[12]
 *   ciphertext (AES-GCM, tag included as the last 16 bytes)
 */
internal class EncryptedFileSecretStore(
  private val appDir: String,
  private val passphrase: String = defaultPassphrase(),
) : SecretStore {

  init {
    ensureDirectory0700(appDir)
  }

  override fun get(account: String): ByteArray? {
    val path = blobFile(account)
    val raw = readFileBytes(path) ?: return null
    if (raw.size < HEADER_SIZE + GCM_TAG_BYTES) return null

    if (raw[0] != 'K'.code.toByte() || raw[1] != 'A'.code.toByte() ||
      raw[2] != 'E'.code.toByte() || raw[3] != 'S'.code.toByte()
    ) return null
    if (raw[4] != 0x01.toByte()) return null

    val salt = raw.copyOfRange(5, 5 + SALT_BYTES)
    val iv = raw.copyOfRange(5 + SALT_BYTES, HEADER_SIZE)
    val ciphertext = raw.copyOfRange(HEADER_SIZE, raw.size)

    val key = deriveKey(salt)
    return decryptWithKey(key, ciphertext, iv)
  }

  private fun decryptWithKey(key: AES.GCM.Key, ciphertext: ByteArray, iv: ByteArray): ByteArray? {
    return runCatching {
      val cipher = key.cipher()
      // dev.whyoleg.cryptography prepends the nonce to ciphertext in encrypt().
      // The stored format (matching JVM) is: header.iv = nonce, blob body = ciphertext||tag.
      // Reconstruct the library's expected input: nonce[IV_BYTES] || ciphertext || tag.
      val withNonce = iv + ciphertext
      runBlocking { cipher.decrypt(withNonce) }
    }.getOrNull()
  }

  override fun put(account: String, value: ByteArray) {
    ensureDirectory0700(appDir)

    val salt = ByteArray(SALT_BYTES).also { CryptographyRandom.nextBytes(it) }

    val key = deriveKey(salt)
    val cipher = key.cipher()
    // encrypt() returns nonce[IV_BYTES] || ciphertext || tag — no explicit IV arg so no AAD.
    val encrypted = runBlocking { cipher.encrypt(value) }
    check(encrypted.size >= IV_BYTES) { "Encrypted output too short (${encrypted.size})" }
    // Extract the nonce generated by the library; store only ciphertext||tag in the blob body.
    // This layout is identical to the JVM EncryptedFileSecretStore format.
    val iv = encrypted.copyOfRange(0, IV_BYTES)
    val ciphertext = encrypted.copyOfRange(IV_BYTES, encrypted.size)

    val out = ByteArray(HEADER_SIZE + ciphertext.size).apply {
      this[0] = 'K'.code.toByte()
      this[1] = 'A'.code.toByte()
      this[2] = 'E'.code.toByte()
      this[3] = 'S'.code.toByte()
      this[4] = 0x01
      salt.copyInto(this, 5)
      iv.copyInto(this, 5 + SALT_BYTES)
      ciphertext.copyInto(this, HEADER_SIZE)
    }

    writeFile0600(blobFile(account), out)
  }

  override fun delete(account: String) {
    unlink(blobFile(account))
  }

  private fun blobFile(account: String): String =
    "$appDir/${sanitize(account)}.aes"

  private fun sanitize(account: String): String =
    account.replace(Regex("[^A-Za-z0-9._-]"), "_")

  private fun deriveKey(salt: ByteArray): AES.GCM.Key {
    val pbkdf2 = CryptographyProvider.Default.get(PBKDF2)
    val derivation = pbkdf2.secretDerivation(
      digest = SHA256,
      iterations = PBKDF2_ITERATIONS,
      outputSize = (AES_KEY_BITS / 8).bytes,
      salt = salt,
    )
    val derivedKey = runBlocking { derivation.deriveSecretToByteArray(passphrase.encodeToByteArray()) }
    val aesGcm = CryptographyProvider.Default.get(AES.GCM)
    return runBlocking { aesGcm.keyDecoder().decodeFromByteArray(AES.Key.Format.RAW, derivedKey) }
  }

  companion object {
    private const val SALT_BYTES = 16
    private const val IV_BYTES = 12
    private const val HEADER_SIZE = 4 + 1 + SALT_BYTES + IV_BYTES // magic + ver + salt + iv
    private const val GCM_TAG_BITS = 128
    private const val GCM_TAG_BYTES = GCM_TAG_BITS / 8
    private const val AES_KEY_BITS = 256
    private const val PBKDF2_ITERATIONS = 200_000

    internal fun defaultPassphrase(): String {
      val user = getpwuid(geteuid())?.pointed?.pw_name?.toKString()?.ifBlank { null }
        ?: getenv("USER")?.toKString().orEmpty()
      val host = getenv("HOSTNAME")?.toKString()?.ifBlank { null } ?: "Linux"
      return "$user\u0000$host"
    }

    fun warnAndCreate(appDir: String): EncryptedFileSecretStore {
      log(
        "EncryptedFileSecretStore",
        "Klardrop: no OS secret service available; storing the device " +
          "identity key in an AES-GCM encrypted file under $appDir. " +
          "This is weaker than a real keyring — install libsecret + secret-tool " +
          "for stronger protection."
      )
      return EncryptedFileSecretStore(appDir)
    }
  }
}
